delivery:
  maxOrders: 10
  minOrders: 1
  
spring:
  application:
    name: forum
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:alura-forum
    username: sa
